FROM node:20-alpine

WORKDIR /app

# FFmpeg for video transcoding
RUN apk add --no-cache ffmpeg

COPY package*.json ./
RUN npm ci --omit=dev

COPY worker ./worker

CMD ["node", "worker/transcode.js"]
