// AUTO-GENERATED from "Clean_Trade_Checklists.docx" (CPR cleaned QC checklists).
// GPT tags each scope task with the matching trade slug(s); the system attaches
// that trade's items here as subtasks. Item text is verbatim from the document.

export interface TradeChecklist {
	trade: string;
	slug: string;
	items: string[];
}

export const TRADE_CHECKLISTS: TradeChecklist[] = [
	{
		trade: 'Demolition',
		slug: 'demolition',
		items: [
			'All designated materials and assemblies are fully removed per scope (flooring, drywall, framing, fixtures, etc.)',
			'Floor areas are cleared to proper substrate where finishes were removed (no remaining wood, tile, thinset, or mud where new finishes will be installed)',
			'All nails, screws, and fasteners are removed or properly set from exposed framing',
			'All demolition areas are clean and properly prepped for next phase (ready for framing, MEP, or finishes)',
			'Corners and transitions are cleaned out and ready for new drywall or finishes',
			'All insulation is fully removed where required (including complete removal of loose fill insulation)',
			'All existing systems (ductwork, plumbing, electrical) are removed as required by scope',
			'All framing designated for removal is fully removed per scope',
			'Doors, windows, and fixtures designated for removal are fully removed and disposed of',
			'Work is performed without unnecessary damage to adjacent areas or surfaces',
			'All debris is removed from interior and exterior (no leftover demo material anywhere on site)',
			'Interior areas are swept and cleaned (no dust piles, scraps, or loose material)',
			'Exterior perimeter is clean and free of debris',
			'No remaining fasteners, sharp objects, or hazards left behind',
			'No partial demo or missed areas (everything in scope is fully removed)',
			'All demo’d areas are fully ready for the next trade (no additional prep required)',
			'No damage to surrounding finishes, structures, or items not included in demo scope',
		]
	},
	{
		trade: 'Concrete',
		slug: 'concrete',
		items: [
			'All work matches plans, approved layout, and agreed scope prior to pour',
			'Forms are straight, square, level, and set to correct finished dimensions',
			'Subgrade and base (including gravel where applicable) are properly compacted and stable',
			'Layout is verified for accuracy, dimensions, and squareness prior to placement',
			'All structural components (footings, rebar, anchor bolts, embeds) are installed per plans and correctly located',
			'Concrete mix and specifications (PSI, etc.) match project requirements',
			'All openings, depressions, and special conditions (door thresholds, sunken areas, etc.) are accounted for prior to pour (verify with plans and GC)',
			'All sleeves, penetrations, and embedded items (plumbing, electrical, irrigation, etc.) are installed and clearly located prior to pour',
			'Finished surfaces are flat, properly sloped where required, and consistent across all areas',
			'All visible edges, steps, and transitions are straight and clean (no irregular or wavy finishes)',
			'Work is performed without damage to surrounding areas or adjacent finishes',
			'All required inspections are completed and passed',
			'No missed items requiring cutting, coring, or correction after pour',
			'No low/high spots or improper slope affecting drainage or finishes',
			'No excessive cracking, chipping, or surface defects',
			'Anchor bolts, embeds, and key locations align with framing and layout requirements',
			'No concrete splatter, staining, or damage to walls, windows, or adjacent surfaces',
			'Control joints are clean, consistent, and properly executed',
			'Work area is fully cleaned (no debris, form material, or leftover concrete)',
		]
	},
	{
		trade: 'Framing',
		slug: 'framing',
		items: [
			'All framing is installed per plans, layout, and agreed scope',
			'The correct lumber is used, as called for in the plans or outlined by project manager',
			'Walls, ceilings, and rooflines are straight, plumb, level, and aligned (no bows, waves, or irregular lines)',
			'All openings (windows, doors, garage doors, pocket doors) are correctly sized and located per plans or GC direction',
			'All openings are square, level, and plumb to allow proper drywall, trim, and door/window installation',
			'All headers, beams, and structural components are installed per plans and properly supported',
			'All required hardware, ties, straps, anchors, bolts, hangers, and connectors are installed per plans',
			'Any post-installed anchors or epoxy anchors requiring special inspection are coordinated and inspected during installation',
			'Stud layout and framing alignment support clean drywall and finish installation (no uneven planes or offsets)',
			'All required backing/blocking is installed (cabinets, vanities, shower glass, handrails, etc.)',
			'HVAC openings (registers and returns) are fully framed/boxed and properly aligned',
			'Framing is coordinated with plumbing, electrical, and HVAC to avoid conflicts or rework',
			'All framing members are properly fastened, secure, and free of damage or overcutting',
			'Work is performed in a way that will not create visible issues in drywall, cabinets, tile, or finish work',
			'No bowed, twisted, or out-of-plane walls or ceilings',
			'No framing misalignment causing issues for drywall, cabinets, tile, or trim',
			'All openings are straight, square, and consistent (no racking, uneven reveals, or prep required by other trades)',
			'No missing or improperly placed backing/blocking',
			'No missing hardware, connectors, or structural components required by plans',
			'No MEP conflicts requiring cutting, relocation, or modification after framing',
			'No damaged, split, or compromised framing members left in place',
			'Rooflines and exterior walls are straight and ready for clean exterior finishes (stucco, siding, etc.)',
			'Work area is clean and free of debris, scrap material, and leftover fasteners',
			'Rough framing and/or shear nail. Structural Steel (if needed)',
			'Post-installed anchor bolts and/or epoxy. If these require special inspection, MUST have that done DURING install. Contact project manager at least 24 hours prior to desired install time.',
		]
	},
	{
		trade: 'Windows/Exterior Doors',
		slug: 'windows_exterior_doors',
		items: [
			'All windows and doors are installed per plans, layout, and agreed scope',
			'All openings are properly prepared and flashed prior to installation',
			'Retrofit windows seamlessly integrate with existing interior and exterior finishes unless otherwise specified',
			'All windows and doors are level, plumb, square, and properly aligned within openings',
			'Units are installed to manufacturer specifications (fastening, shimming, spacing, and support)',
			'All units operate smoothly and correctly (open, close, lock, latch)',
			'All units are properly sealed, weather-tight, and air-tight',
			'Flashing, sealants, and transitions are properly installed and integrated with surrounding weather barrier (WRB)',
			'Door thresholds are level and properly set for finished floor conditions (verify with GC if unclear)',
			'All required components are installed (screens, hardware, locks, keys, etc.)',
			'All exterior penetrations and joints are properly sealed to prevent water intrusion',
			'Installation is coordinated with exterior finish system (stucco, siding, etc.) to ensure proper integration',
			'Work is performed without damage to windows, glass, frames, or surrounding finishes',
			'No units out of level, plumb, or square',
			'No binding, sticking, or improper operation of windows or doors',
			'No air gaps, water intrusion points, or incomplete sealing',
			'No missing flashing, improper laps, or exposed areas',
			'No visible gaps at frames, thresholds, or transitions',
			'No damage to glass, frames, hardware, or finishes',
			'No excessive or messy caulking (all sealant lines clean and controlled)',
			'No leftover debris, or installation residue on units',
			'All surrounding surfaces are clean and free of caulk, foam, or damage. All job debris is clean and removed.',
		]
	},
	{
		trade: 'HVAC',
		slug: 'hvac',
		items: [
			'All work matches plans, equipment specs, and agreed scope',
			'All HVAC units and equipment are installed in correct locations and properly supported',
			'All boots, plenums, returns, and duct runs are installed in correct locations per layout',
			'All registers, returns, and grilles are aligned, square, and consistently located relative to walls, ceilings, and cabinets',
			'Ductwork is properly routed, supported, and secured (no kinks, sags, or restrictions)',
			'System layout is coordinated with framing, lighting, and other trades (no conflicts with fixtures, fans, or structure)',
			'All required ventilation systems are installed and properly routed (bath fans, kitchen hood, makeup air if required)',
			'Kitchen hood ducting is properly sized and installed per appliance specifications',
			'All penetrations through framing, walls, and roof are properly sealed and protected',
			'All required clearances and spacing are maintained',
			'System is installed per manufacturer specifications and applicable codes',
			'Work is performed without damage to surrounding framing or finishes',
			'No misaligned or crooked registers, returns, or grilles',
			'No conflicts with lights, ceiling fans, cabinets, or other fixtures',
			'No sagging, kinked, or poorly supported ductwork',
			'No missing or improperly installed vents (bath fans, hood, makeup air, etc.)',
			'No excessive noise, airflow restriction, or obvious performance issues',
			'All penetrations are properly sealed (no visible gaps at walls, ceilings, or roof)',
			'All grilles and registers are installed flush, clean, and undamaged',
			'No debris, dust, or construction material left in ducts or registers',
			'Work area is fully cleaned (no scrap material, fasteners, or debris left behind)',
		]
	},
	{
		trade: 'Plumbing',
		slug: 'plumbing',
		items: [
			'UNDERGROUND PLUMBING',
			'All work matches plans, approved layout, and agreed scope',
			'Water supply, sewer, and gas systems are sized and installed per plans and requirements',
			'All underground piping is properly located, sloped, and aligned for intended fixtures',
			'All fixture locations (islands, bathrooms, tubs, etc.) are verified and coordinated prior to installation',
			'All plumbing stubs are installed in correct locations and within wall/floor cavities (no interference with framing, drywall,',
			'or finishes)',
			'All required stubs (water, waste, gas, island vents, etc.) are accounted for and properly located',
			'All rough stubs are protected, wrapped, or boxed where required',
			'Special fixtures (freestanding tubs, island sinks, etc.) are accounted for and properly located',
			'Work is coordinated with GC and other trades to avoid conflicts or relocation later',
			'All work is installed per code, plans, and applicable standards',
			'No misplaced or incorrectly located stubs requiring relocation',
			'No stubs protruding outside wall plane or interfering with drywall or finishes',
			'No missing stubs for fixtures, islands, or exterior locations',
			'No slope issues or layout errors affecting drainage',
			'All stubs are protected and ready for next phase',
			'No conflicts with framing, slab, or other systems',
			'Work area is clean and free of debris or leftover materials',
			'ABOVE GROUND PLUMBING',
			'All work matches plans, approved layout, and agreed scope',
			'All water, waste, vent, and gas lines are properly installed, supported, and secured',
			'All fixture locations (valves, heads, spouts, supplies) are installed at correct height and position per plans or GC direction',
			'All plumbing components are coordinated with framing, cabinetry, tile, and finishes (e.g. toilet stubs do not interfere with baseboards',
			'All lines are properly supported within walls and ceilings (no movement or flex)',
			'Nail plates are installed where required',
			'All penetrations are properly sealed (fire caulked or foamed where required)',
			'All venting is installed and properly routed',
			'Gas lines are properly sized and installed for intended fixtures (no undersized or improper materials causing performance issues)',
			'All required specialty items are installed where applicable (recirc lines, softener loops, appliance connections, etc.)',
			'Appliance and fixture connections (fridge, tubs, showers, etc.) are installed in correct locations per specs',
			'Tubs and fixtures are properly set and supported per manufacturer requirements',
			'Work is installed per code, plans, and applicable standards',
			'No incorrectly located valves, stubs, or fixtures requiring adjustment after finishes',
			'No plumbing interfering with drywall, cabinets, tile, or trim (including baseboards and enclosures)',
			'No loose or unsupported pipes, valves, or fixtures',
			'No missing connections or required components (recirc, softener loop, gas stubs, etc.)',
			'No gas line sizing or material issues affecting performance (e.g. whistling or restriction)',
			'All fixtures are installed correctly and function as intended (hot/cold orientation, alignment, secure mounting)',
			'No visible gaps at penetrations or unfinished sealing',
			'No damage to surrounding surfaces or finishes',
			'Work area is clean and free of debris or leftover materials',
			'Water/sewer/soil/copper Water Meter',
			'Rough Plumbing Gas Piping/Pressure Test',
		]
	},
	{
		trade: 'Electrical',
		slug: 'electrical',
		items: [
			'All work matches plans, approved layout, and agreed scope',
			'Panel size, breakers, and circuits match plans and load requirements',
			'Panels are properly labeled and clearly identified',
			'All outlets, switches, lighting, and electrical components are installed in correct locations per plans or GC direction',
			'Appliance, island, and specialty locations are verified against appliance specs and layout prior to installation',
			'All boxes are installed straight, level, securely supported, and set to correct depth for finished surfaces',
			'All recessed lights are laid out straight, evenly spaced, and aligned with walls, cabinets, and key features',
			'All wiring is properly routed, protected, and secured (including nail plates where required)',
			'All required systems are installed (low voltage, lighting, floor outlets, fireplace wiring, etc.)',
			'All required grounding and bonding is installed (including water/gas bonds and ufer where required)',
			'All penetrations through framing are properly sealed (fire caulked or foamed where required)',
			'All rough-in wiring for future fixtures or features is properly located and accounted for',
			'All work is coordinated with framing, cabinetry, tile, and other trades to avoid conflicts',
			'Work is installed per code, plans, and applicable standards',
			'No misaligned outlets, switches, or fixtures (all are straight, level, and consistently positioned)',
			'All recessed lights are perfectly straight, evenly spaced, and visually aligned',
			'No boxes set too deep or proud of finished surfaces (including backsplash areas requiring adjustable boxes)',
			'All outlets, switches, and cover plates are flush, level, and cleanly installed (aligned screws where visible)',
			'All recessed light trims are flush to ceiling and consistent in color temperature',
			'No missing wiring or unaccounted-for future connections behind drywall',
			'No electrical conflicts with cabinets, tile, appliances, or trim',
			'All floor outlets and specialty locations are properly installed and finished',
			'No exposed wires, unfinished penetrations, or incomplete sealing',
			'All components function properly and are ready for use',
			'Work area is clean and free of debris, scrap wire, and leftover materials',
			'Footing/Ufer Temp Power',
		]
	},
	{
		trade: 'Insulation',
		slug: 'insulation',
		items: [
			'All insulation is installed per plans, specifications, and agreed scope',
			'Correct insulation type and R-value are installed in all required locations',
			'All wall, ceiling, and roof cavities are fully and consistently insulated (no gaps, voids, or missed areas)',
			'Insulation is installed properly within framing and will not interfere with drywall or finishes',
			'Spray foam is properly applied and trimmed flush where required to allow proper drywall installation',
			'Vapor barrier is installed where required and properly integrated',
			'All required sound insulation is installed per plans or scope',
			'Insulation does not block or restrict roof, attic, or eave ventilation',
			'Windows, doors, and penetrations are properly sealed or insulated where required',
			'Installation is coordinated with other trades to ensure all areas are accessible and complete prior to close-up',
			'Work is installed per code, plans, and applicable standards',
			'No missing insulation in any required areas (walls, ceilings, or transitions)',
			'No insulation protruding past framing that will interfere with drywall',
			'No gaps, voids, or compressed areas reducing effectiveness',
			'No blocked vents, soffits, or airflow paths',
			'Spray foam is properly trimmed and does not affect finishes',
			'No incorrect insulation type or R-value in any area',
			'All windows, doors, and penetrations are properly sealed',
			'Work area is clean and free of debris, excess material, or overspray',
		]
	},
	{
		trade: 'Drywall',
		slug: 'drywall',
		items: [
			'All drywall is installed per plans, specifications, and agreed scope',
			'Correct drywall type and thickness are used in all required areas (including fire-rated and wet areas)',
			'Cement board or tile backer is installed where required',
			'All fixture, switch, and outlet boxes are properly cut out and accessible',
			'All wiring (electrical, low voltage, thermostat, etc.) is properly located and accessible',
			'All boards are installed flat and aligned (no bulging, sagging, or uneven planes)',
			'Joints are properly taped, finished, and blended for required finish level',
			'All surfaces are properly sanded and prepared for paint per specified finish level',
			'Skim coat (if applicable) is properly applied and sanded without interfering with trim, baseboards, or finishes',
			'Corners, returns, and openings (windows, doors, niches) are straight, square, plumb, and tight',
			'Control joints are installed where required',
			'Work is coordinated with framing, MEP, and finishes to ensure proper alignment and fit',
			'Floors and surrounding surfaces are properly protected during installation',
			'No visible seams, joints, or imperfections that will show through paint (including in direct light)',
			'No uneven or wavy wall or ceiling surfaces',
			'No buildup at joints, corners, or transitions affecting trim or finishes',
			'No missed sanding, rough areas, or dust left on surfaces',
			'No gaps or irregularities at windows, doors, or returns',
			'All closets, bathrooms, and small areas are finished to same quality as main areas',
			'No drywall interfering with electrical boxes, fixtures, or trim installation',
			'No damage to floors, windows, doors, or surrounding surfaces',
			'All surfaces are clean and free of drywall mud, dust, and debris',
			'Work area is fully cleaned and ready for next trade',
		]
	},
	{
		trade: 'Flooring',
		slug: 'flooring',
		items: [
			'All flooring is installed per plans, layout, and agreed scope',
			'Substrate is properly prepared, flat, clean, and suitable for flooring installation',
			'Flooring is installed flat and consistent (no deflection, soft spots, or uneven areas)',
			'If leveling is needed, inform GC or Project Manager immediately and prior to installation',
			'Layout is straight, aligned with the space, and visually consistent (no drifting or tapering)',
			'Joints, seams, or plank alignment are consistent and properly spaced',
			'Transitions between flooring and adjacent materials (tile, cabinets, walls, etc.) are clean and properly detailed',
			'Perimeter gaps and expansion requirements are properly maintained where required',
			'Cuts at walls, cabinets, and penetrations are clean and properly located',
			'Flooring installation is coordinated with cabinets, doors, and trim for proper fit and finish',
			'All materials are installed per manufacturer specifications',
			'Work is performed without damage to flooring or surrounding surfaces',
			'No soft spots, deflection, or uneven areas in flooring',
			'No visible gaps, lippage, or inconsistent joints/seams',
			'No drifting, tapering, or misaligned layout',
			'No damage to flooring (scratches, chips, dents, or defects)',
			'All cuts are clean and properly concealed by baseboards, trim, or transitions',
			'All transitions are straight, secure, and visually consistent',
			'No improper spacing at walls or missing expansion gaps where required',
			'No interference with doors, cabinets, appliances, or trim',
			'Flooring is clean and free of dust, adhesive, residue, or installation marks',
			'No conditions exist that will require removal, repair, or adjustment after proceeding',
		]
	},
	{
		trade: 'Cabinetry',
		slug: 'cabinetry',
		items: [
			'All cabinets are installed per approved layout, plans, and agreed scope',
			'All cabinets are level, plumb, and properly aligned across all runs',
			'Cabinets are securely fastened and properly joined (no gaps between boxes)',
			'All cabinet elevations and layout align with adjacent finishes (floors, walls, ceilings, and appliances)',
			'All doors, drawers, and panels are installed straight, square, and properly spaced',
			'All hardware (hinges, slides, pulls, etc.) is installed per plan and functions properly',
			'All doors and drawers open, close, and align correctly',
			'All filler pieces, scribes, panels, and trim are properly installed and fit cleanly to surrounding surfaces',
			'All crown molding and trim are straight, tight, and properly aligned',
			'All required backing and support is in place for wall-hung or floating cabinets and shelves',
			'All built-in accessories (pull-outs, inserts, trash systems, etc.) are installed per plan',
			'Cabinet installation is coordinated with electrical, plumbing, and lighting (no covered wires or conflicts)',
			'All cabinets are installed ready for countertop installation (including proper support and layout)',
			'Work is performed without damage to materials, finishes, or surrounding surfaces',
			'No cabinets out of level, plumb, or alignment',
			'No gaps between cabinet boxes, fillers, or adjacent surfaces',
			'All doors and drawers are aligned evenly with consistent spacing and reveals',
			'All hardware operates smoothly and is properly adjusted',
			'No damage to cabinets, doors, drawers, or finishes (scratches, chips, glue, etc.)',
			'All nail holes and fasteners are properly filled and finished',
			'All crown, trim, and scribe pieces are tight, clean, and visually consistent',
			'All toe kicks are installed and complete',
			'All floating cabinets and shelves are secure and properly supported',
			'Wood grain alignment is consistent where required',
			'No interference with appliances, plumbing, electrical, or lighting',
			'All surfaces are clean and free of dust, debris, or installation residue',
		]
	},
	{
		trade: 'Tile',
		slug: 'tile',
		items: [
			'All work matches plans, approved layout, and agreed scope',
			'All wet areas are properly waterproofed prior to tile installation',
			'Shower pans are properly sloped to drain',
			'All tile layout, patterns, and termination points are verified prior to installation',
			'Tile requiring sealing (e.g. natural stone, cement) has been sealed properly prior to installation if required',
			'All niches, benches, shelves, and features are installed per plans and properly integrated',
			'Wall and floor tile are installed flat, level, and properly aligned',
			'Tile spacing and grout joint size are consistent throughout',
			'All cuts (edges, corners, drains, penetrations) are clean, accurate, and properly located',
			'All penetrations (valves, outlets, fixtures, etc.) are properly cut to allow full coverage by finish trim',
			'Tile transitions and terminations (Schluter, edges, height changes, etc.) are properly installed',
			'Installation is coordinated with cabinets, appliances, plumbing, and trim for proper layout and fit',
			'All surfaces are prepared and installed to support proper adhesion and long-term performance',
			'Work is performed without damage to tile, materials, or surrounding surfaces',
			'No lippage (uneven tile edges) on floors or walls',
			'No uneven or inconsistent grout joints',
			'No chips, cracks, or damaged tiles',
			'Grout is fully installed, consistent, and free of holes or voids',
			'Grout color matches approved selection',
			'No grout haze or residue left on tile surfaces',
			'All cuts are clean and properly aligned (including around drains, edges, and penetrations)',
			'All tile layout is straight and visually consistent (no drifting or misalignment)',
			'Tile terminates correctly at walls, cabinets, appliances, and shower glass locations',
			'No gaps or exposed areas at penetrations or edges',
			'Tile is properly positioned to be covered by baseboards or trim where required',
			'No interference with fixtures, appliances, or finish elements',
			'Work area is clean and free of debris, grout, or residue',
			'Shower Pan/Waterproofing Other__________________',
		]
	},
	{
		trade: 'Doors & Millwork',
		slug: 'doors_millwork',
		items: [
			'All doors and millwork are installed per plans, layout, and agreed scope',
			'All doors are correct size, swing, and type per plan (verify prior to install if unclear)',
			'All jambs are correct width and properly set for wall and finish conditions',
			'All doors are installed plumb, level, and square, and properly shimmed and secured',
			'All doors operate correctly (open, close, latch, and align properly)',
			'Door bottoms are properly trimmed for finished flooring conditions',
			'All hardware (hinges, handles, tracks, etc.) is installed per plan and functions properly',
			'Specialty doors (pocket, bifold, bypass) are properly installed and adjusted',
			'All casing, baseboard, and millwork are installed straight, level, and aligned',
			'All reveals at doors, windows, and openings are consistent and uniform',
			'All miters and joints are tight, flush, properly glued, and cleanly finished',
			'All millwork terminates cleanly at floors, walls, and adjacent materials',
			'Installation is coordinated with flooring, cabinets, and drywall for proper fit and alignment',
			'All nails are properly set for finishing',
			'Work is performed without damage to doors, millwork, or surrounding surfaces',
			'No doors out of plumb, misaligned, or swinging on their own',
			'All doors latch properly and align correctly with strikes',
			'No rubbing, binding, or clearance issues at floors or frames',
			'All door hardware functions properly and is installed correctly',
			'No gaps at jambs, casing, baseboards, or floor transitions',
			'All reveals are consistent and visually aligned across all openings',
			'All miters are tight, flush, and free of gaps or separation',
			'No damage to doors, trim, or millwork (chips, dents, scratches, etc.)',
			'All specialty doors (pocket, bifold, bypass) operate smoothly and align properly',
			'Baseboards and trim are tight to floors and walls (no gaps or poor scribing)',
			'All adjacent openings and trim lines align consistently across the space',
			'All closets and secondary areas are finished to same standard as main areas',
			'No visible fasteners, unfinished nail holes, or installation defects',
			'Work area is clean and free of debris or leftover materials',
		]
	},
	{
		trade: 'Interior Paint',
		slug: 'interior_paint',
		items: [
			'All work matches plans, finish level, and agreed scope',
			'All surfaces (walls, ceilings, trim, floors) are clean and free of dust, debris, and contaminants prior to prep',
			'All drywall joints, nail holes, and imperfections are properly filled, sanded, and prepared for paint',
			'All caulking is properly applied, smooth, and clean prior to painting',
			'All corners and edges are sharp, square, and properly finished (no rounded or overfilled edges)',
			'All surfaces are properly sanded and prepared for primer and paint',
			'All new drywall is properly dusted and primed prior to painting',
			'All masking and protection is properly installed to protect adjacent surfaces',
			'Paint is applied per specifications (including backrolling where required)',
			'All paint lines, transitions, and cut-ins are clean, straight, and properly defined',
			'All surfaces are finished smooth and free of dust, debris, or contamination during application',
			'Work is performed without damage to adjacent finishes, fixtures, or materials',
			'No visible dust, debris, or contamination under paint (“painted over dust”)',
			'No visible imperfections in walls, ceilings, or trim after paint (patches, ridges, or rough areas)',
			'No overspray, paint marks, or damage on floors, cabinets, fixtures, outlets, or adjacent surfaces',
			'All cut lines are sharp and clean (no bleed, gaps, or uneven transitions)',
			'No paint buildup, drips, runs, or sprayer defects',
			'All corners are clean, sharp, and consistent',
			'All caulk lines are smooth, clean, and properly finished',
			'All caulk is painted where used in finishing',
			'All outlets, switches, fixtures, and hardware are clean and free of paint',
			'All surfaces have consistent coverage, color, and finish (no flashing or inconsistency)',
			'All areas (including closets and secondary spaces) are finished to same standard as main areas',
			'All materials and leftover paint are properly labeled and organized',
			'Work area is clean and free of dust, masking, and debris',
		]
	},
	{
		trade: 'Exterior Paint',
		slug: 'exterior_paint',
		items: [
			'All work matches plans, color selections, and agreed scope',
			'All surfaces are properly prepared prior to painting (clean, dry, and free of dust, dirt, chalking, or contaminants)',
			'All surfaces are properly scraped, sanded, and repaired where needed prior to paint',
			'All cracks, joints, and penetrations are properly sealed and caulked',
			'All surfaces are properly primed where required',
			'All masking and protection is properly installed to protect windows, doors, fixtures, roofing, concrete, and surrounding',
			'surfaces',
			'Paint is applied per specifications (including backrolling where required)',
			'Paint is applied below grade at stems and foundations where necessary.',
			'All paint lines, transitions, and cut-ins are clean, straight, and properly defined',
			'All surfaces receive consistent and even coverage across all elevations',
			'Application is coordinated with weather conditions to ensure proper adhesion and finish',
			'All penetrations, fixtures, and transitions are properly sealed and finished',
			'Work is performed without damage to surrounding materials or finishes',
			'No visible overspray, paint marks, or damage on windows, doors, glass, roofing, concrete, or adjacent surfaces',
			'No visible peeling, flashing, lap marks, or inconsistent finish across elevations',
			'No missed areas or thin coverage (including edges, soffits, trim, and behind elements)',
			'All cut lines are sharp and clean (no bleed, gaps, or uneven transitions)',
			'No paint buildup, drips, runs, or sprayer defects',
			'Grade is properly restored if moved away from foundation during painting',
			'All caulk lines are smooth, clean, and properly finished',
			'No exposed raw material or unpainted surfaces where coverage is required',
			'All color transitions and material transitions are clean and consistent',
			'All fixtures, vents, outlets, and penetrations are clean and properly detailed',
			'All masking is removed and all surfaces are clean',
			'Work area is clean and free of debris, masking, and paint residue',
		]
	},
];

export const TRADE_CHECKLIST_SLUGS = TRADE_CHECKLISTS.map((c) => c.slug);
export function getTradeChecklist(slug: string): TradeChecklist | undefined {
	return TRADE_CHECKLISTS.find((c) => c.slug === slug);
}
